version: '3.7'

services:
  etny-pynithy:
    image: docker_etny-pynithy1
    # build:
    #    context: .
    #    dockerfile: docker_etny-pynithy1
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    devices:
      - /dev/isgx
    environment:
      - SCONE_HEAP=256M 
      - SCONE_MODE=HW
      - SCONE_ALLOW_DLOPEN=2
      - SCONE_ALPINE=0
      - SCONE_VERSION=1
      - SCONE_LOG=0
    working_dir: /myapp
    